### ISSUE TITLE
Profiler child process fails to connect to the server on Windows

### ISSUE THREAD

**Issue by vkazanov** [jschaf/esup#18]
Esup starts the child, but the child fails to connect to the server process saying something like: "Unknown service port: <esup-server-port-here>"

I've looked into the problem and found out that the `esup-child-run` function gets the port arg as a string, while something within `esup-child-init-stream` expects a number. `string-to-number` helps here.

This happens on my Windows 7 machine, with Emacs 24.4.1. Do not have the Linux machine right now, cannot check if it helps there.

**Comment by jschaf** [comment]
I'll see if I can reproduce on Windows.  Lemme know if it works on Linux

**Comment by jschaf** [comment]
I reproduced on Windows.  Your suggestion of string-to-number seemed to do the trick.  Lemme know if it works for you.

**Comment by vkazanov** [comment]
Yes, it does, don't know about linux though.
