### ISSUE TITLE
open-network-stream: localhost/54042 System error

### ISSUE THREAD

**Issue by cocreature** [jschaf/esup#19]
When I run `M-x esup` a new emacs window pops up and in `*Messages*` there are only two lines. I have no idea what could be causing this.

```
For information about GNU Emacs and the GNU system, type C-h C-a.
open-network-stream: localhost/54042 System error
```

edit: here is my emacs config https://github.com/cocreature/dotfiles/blob/master/emacs/.emacs.d/emacs.org

**Comment by jschaf** [comment]
Could you show the output of `emacs-version`

**Comment by cocreature** [comment]
`GNU Emacs 24.4.2 (x86_64-unknown-linux-gnu, GTK+ Version 2.24.25) of 2015-02-26 on localhost`

**Comment by jschaf** [comment]
Is this still an issue?  I think it might have been fixed on https://github.com/jschaf/esup/issues/18.

**Comment by jschaf** [comment]
If it's still an issue, please reopen.
