### ISSUE TITLE
`with-slots` is problematic on Emacs 24.3

### ISSUE THREAD

**Issue by oantolin** [jschaf/esup#27]
I'm stuck with Emacs 24.3 at work and recently tried using `esup`. It failed at the step of rendering the results, producing an error message saying that `expression-string` is undefined. The problem is in the function `render` which makes use of `with-slots`. Apparently on Emacs 24.3 the `with-slots` macro expands to use `symbol-macrolet` instead of `cl-symbol-macrolet`; but esup.el requires `cl-lib` and not `cl`. I found two ways to get it to work: 1) rewriting the function to avoid with-slots (i.e., replacing `file` with `(oref obj :file)`), 2) adding a `(require 'cl)`.

With either of those changes it works just fine.

**Comment by jschaf** [comment]
Ok, I'll add a test for the emacs version and pull in the right file.

**Comment by jschaf** [comment]
Lemme know if that change worked.  If it didn't I'll reopen.

**Comment by oantolin** [comment]
Yes, that worked, thanks!
