### ISSUE TITLE
Esup gives an error: Args out of range: "", 1

### ISSUE THREAD

**Issue by ReneFroger** [jschaf/esup#31]
When I call esup with <kbd>M-x esup</kbd>, then I see a new frame popping up,

and ends it directly. In the `*messages*` buffer, I see only the message

    Args out of range "", 1

Bisecting my init.el didn't help (as in comment out big parts of my init.el). What would you suggest to do?

**Comment by jschaf** [comment]
This sounds similar to https://github.com/jschaf/esup/issues/20

Can you post the contents of `*esup-log*`?  It's a hidden buffer, but it exists after running `esup`.

What OS are you using?

What emacs version?

**Comment by jschaf** [comment]
Also, do you happen to use spacemacs?  I just hit this bug.

**Comment by jschaf** [comment]
Fixed in https://github.com/jschaf/esup/commit/44f8fe5ff8d926fbd134e7aef67bb004a720403a
