### ISSUE TITLE
Process *esup-child* exited abnormally with code 1

### ISSUE THREAD

**Issue by hhnr** [jschaf/esup#34]
Steps to reproduce:
1. run emacs in terminal (``` emacs -nw```)
2. run esup (```M-x esup```)
3. in minibuffer, ```esup started on port 35402```.
4. in the current buffer ```Process *esup-child* exited abnormally with code 1 is displayed```.
5. GNU Emacs 24.5.1 (i686-pc-linux-gnu) of 2015-12-11 built with``` --without-x```. Does this package need GUI version of emacs to work properly?

**Comment by hhnr** [comment]
After installing GUI version of emacs, ```M-x esup``` works fine.

**Comment by jschaf** [comment]
When esup starts, it launches another emacs process.  What's happening is that when you try to launch another terminal Emacs from a terminal, Emacs is trying to run itself.  I just tried it and here's the error output.

```
emacs: Terminal type "dumb" is not powerful enough to run Emacs.
It lacks the ability to position the cursor.
If that is not the actual type of terminal you have,
use the Bourne shell command 'TERM=...; export TERM' (C-shell:
'setenv TERM ...') to specify the correct type.  It may be necessary
to do 'unset TERMINFO' (C-shell: 'unsetenv TERMINFO') as well.

Process EMACS exited abnormally with code 1
```

Actually using esup on only terminal Emacs is a little beyond the scope of this project.  That would involve staring new terminals and running emacs inside the new terminal.
