### ISSUE TITLE
emacs-init-time != esup startup time?

### ISSUE THREAD

**Issue by matthewbauer** [jschaf/esup#42]
I've been trying to speed things up with esup, but I'm having trouble understanding why it is giving me so different numbers from emacs-init-time:

```
(emacs-init-time) => .8 seconds

(esup) => .194 seconds
```

Maybe this just needs to be documented better. I suspect it has to do with emacs-init-time starting earlier than esup is able to?

**Comment by jschaf** [comment]
Yes, part of the time is in emacs internals that esup can't profile see.  On my system, if I do `emacs -q` and then `emacs-init-time` I get 0.6 seconds.

What's your emacs-init-time with `emacs -q`?  I suspect that's the difference.

**Comment by matthewbauer** [comment]
Yeah I'm getting .3 seconds with emacs-init-time on emacs -q.

**Comment by jschaf** [comment]
So, there's still a discrepancy. I'm not sure where the overhead is coming from.

**Comment by matthewbauer** [comment]
Yeah, I suspect it has something to do with the way Mac starts up applications...
