### ISSUE TITLE
Process *esup-child* exited abnormally with code 1

### ISSUE THREAD

**Issue by onlynone** [jschaf/esup#45]
When I run esup, I get this message written to the top of the buffer I currently have open:

    Process *esup-child* exited abnormally with code 1

And at the bottom of the screen I see:

    esup process started on port 58085

**Comment by jschaf** [comment]
There's a hidden buffer called `*esup-log*` which will have more detail.  I'm closing this in favor of #40.   If there's a separate problem, please re-open and rename the bug.
