### ISSUE TITLE
esup stops profiling after string

### ISSUE THREAD

**Issue by dinkonin** [jschaf/esup#47]
Esup stops profiling after parsing a formatted string here is my code
```
(defun display-startup-echo-area-message ()
  "Emacs startup time"
      (message "Load time is %s" (emacs-init-time)))
```

This is the error message:

> LOG: profiling sexp ~/.emacs.d/init.el:25 (defun display-startup-echo-ar
> LOG: ERROR(profile-sexp) at ~/.emacs.d/init.el:25: (error Not enough arguments for format string)
> name: *esup-server* <127.0.0.1:22557>, sentinel: proc: *esup-server* <127.0.0.1:22557>, event connection broken by remote peer

The same thing happens with this code:
`(setq  frame-title-format "%@%b%*")`

I'm using Emacs 25.2.1 on Windows

**Comment by et2010** [comment]
I've got the same issue.

**Comment by jschaf** [comment]
I can reproduce.  It's most likely an error in the actual profiling code.

**Comment by jschaf** [comment]
Okay, everything is working again.  Thank you for reporting the bug.
