### ISSUE TITLE
esup fails to run on macOS High Sierra / Emacs 25.3

### ISSUE THREAD

**Issue by deybhayden** [jschaf/esup#51]
Hey there, thanks for this great plugin! I recently started having some problems running `M-x esup`

<img width="666" alt="screen shot 2018-03-28 at 4 45 00 pm" src="https://user-images.githubusercontent.com/877908/38058178-93419e5a-32a7-11e8-9148-1225ec7d2cff.png">

The `*Messages*` buffer has this:

```
For information about GNU Emacs and the GNU system, type C-h C-a.
Error: (void-function vc-git-root)
esup-child-send-log: Process *esup-child-connection* not running
```

Any ideas (this probably worked about a 2-3 weeks ago)?

**Comment by zaript** [comment]
I also have an issue in MacOS, not sure if it's related or completely different:

```
Starting esup...
esup process started on port 50709
at 1
error in process sentinel: eieio-oref: Wrong type argument: (or eieio-object class), nil, obj
error in process sentinel: Wrong type argument: (or eieio-object class), nil, obj
```

Emacs version:
```
GNU Emacs 25.3.1 (x86_64-apple-darwin17.4.0, NS appkit-1561.20 Version 10.13.3 (Build 17D102)) of 2018-03-08
```

**Comment by casouri** [comment]
This happens on Emacs 26, High Sierra too.

**Comment by CeleritasCelery** [comment]
+1 for Emacs 25.1 on SUSE Linux. Seeing `Error: (void-function vc-git-root)`

**Comment by gmjain** [comment]
+1 for emacs 25.3.
Seeing the same eieio-oref issue as @zaript.

Will help in anyway I can. :-)

**Comment by jschaf** [comment]
Hey all, as a hot-fix I'll reduce the reduce profile depth to see if that addresses the issue.

**Comment by jschaf** [comment]
I think it has to do with how esup intercept require calls.  I switched it to use advice instead of parsing the elisp.  The advice is much more robust, but has the unintended side-effect of intercepting require calls that don't appear in dotfiles.

When loading a vc-controlled file, emacs loads vc-git which esup happily starts profiling.  This isn't useful behavior

To fix it, esup should only intercept require calls that appear directly in dotfiles.

**Comment by CeleritasCelery** [comment]
@jschaf, that fixed the issue for me (the error that this issue was created for: `(void-function vc-git-root)`). Thanks!

**Comment by zaript** [comment]
Seems to be fixed with latest version of esup and Emacs 26.1.

**Comment by jeffbowman** [comment]
Still seeing this with Emacs 26.1:
Starting esup...
esup process started on port 39165
at 1
error in process sentinel: eieio-oref: Wrong type argument: (or eieio-object class), nil, obj
error in process sentinel: Wrong type argument: (or eieio-object class), nil, obj

for reference, my configuration is at https://bitbucket.org/jeffbowman/dotfiles

**Comment by zaript** [comment]
@jeffbowman Occasionally I manage to fix things by deleting all *.elc files in .emacs.d. Things start working after recompilation.

**Comment by matthew-piziak** [comment]
Still seeing this on Emacs 26.1 with today's version of esup and all `elc` files freshly recompiled.

**Comment by matthew-piziak** [comment]
Oh is _that_ what it is? I also use `straight.el`.

**Comment by CeleritasCelery** [comment]
I am also seeing this again after switching to straight.el. Not sure which package is at fault.

**Comment by taigacute** [comment]
@jschaf  got same error with straight on emacs 28

**Comment by Gahamelas** [comment]
Same error ) esup-child-send-log: Process *esup-child-connection* not running". Any ideas?

**Comment by casouri** [comment]
Maybe you can try this: https://github.com/dholm/benchmark-init-el

**Comment by Gahamelas** [comment]
Thanks, I will try.
