### ISSUE TITLE
Doesn't work on macOS with emacs-plus 26.0.91

### ISSUE THREAD

**Issue by bwolf** [jschaf/esup#52]
Recently I started using the development version of Emacs to get the vfork patch. Unfortunately esup stopped working for me with GNU Emacs 26.0.91 on macOS 10.13.4. Emacs is installed via `brew install emacs-plus --devel`.

When running `esup` I get:

```
Debugger entered--Lisp error: (wrong-type-argument (or eieio-object class) nil obj)
  signal(wrong-type-argument ((or eieio-object class) nil obj))
  eieio-oref(nil :expression-string)
  esup-fontify-results((#<esup-result esup-result> ... #<esup-result esup-result> nil))
  esup-display-results()
  esup-child-process-sentinel(#<process *esup-child*> "finished\n")
```

Please note that I truncated the output of `esup-fontify-results (( ))`, indicated by `...`.

**Comment by Yevgnen** [comment]
Same but I'm using `emacs-mac`.
