### ISSUE TITLE
[Bug] - No indentation in  *esup* buffer.

### ISSUE THREAD

**Issue by jcs090218** [jschaf/esup#63]
Can you make so all the code in `*esup*` buffer the same in the configuration including the indentation?

**Edit:** I thought this is something that hasn't be implemented. Apparently, I was wrong so I assume this is the bug I encountered.

![no-indent](https://user-images.githubusercontent.com/8685505/59323729-7ac06b00-8d0e-11e9-8a55-2bf84fec5401.png)

As the image, there are no indentation in the buffer. Not quite sure what I did wrong?

**Comment by sergeyklay** [comment]
@jcs090218 I'm interested to fix this (or at least sorting it out).  Could you please provide the expected result.

**Comment by jcs090218** [comment]
The expect result should be same as the bottom from the image shown with just not having the indentation of 2.

```el
(use-package diminish
  :defer t
  : config
  ...
```

Thanks! 😄

**Comment by benley** [comment]
It appears that using `string-trim` from `subr-x.el` in place of the current `esup-child-chomp` function would fix this problem.

**Comment by jcs090218** [comment]
Any progress on this? Thanks! 😄

**Comment by sergeyklay** [comment]
> Any progress on this? Thanks! smile

Nope :( I can't find enough free time. I'm sorry

**Comment by benley** [comment]
I think I have a viable fix for this now: https://github.com/jschaf/esup/pull/80

**Comment by sergeyklay** [comment]
@jcs090218 AFAIK it is fixed now. Could you please check?

**Comment by jcs090218** [comment]
I got an error with `Cannot open load file: No such a file or directory, s`. 😕 

I believe is something wrong with the patch #80?

**Comment by benley** [comment]
> I got an error with `Cannot open load file: No such a file or directory, s`. 😕
> 
> I believe is something wrong with the patch #80?

#80 introduces a dependency on s.el, which is supposedly covered by the comment header change in esup-child.el.  But maybe that's not enough to make package.el notice it - do we need to also add the `s` dependency in esup.el directly?  Is there another place dependency info hides?

**Comment by jcs090218** [comment]
I actually have not idea, does anyone having the same issue as me? Or just me? 😖
