### ISSUE TITLE
Refactor tests to use buttercup

### ISSUE THREAD

**Issue by sergeyklay** [jschaf/esup#76]
Presently `esup` use [ert](https://www.gnu.org/software/emacs/manual/html_node/ert/index.html) through [ert-runner](https://github.com/rejeep/ert-runner.el) for testing purposes. However, it seems `ert-runner` is abandoned (the last commit a few years ago), it still uses only Emacs 24 on its own tests and in general it looks as [not maintained](https://github.com/rejeep/ert-runner.el/issues/15) [anymore](https://github.com/rejeep/ert-runner.el/issues/44) [project](https://github.com/rejeep/ert-runner.el/issues/49).

It seems we need to migrate our tests to use [buttercup](https://github.com/jorgenschaefer/emacs-buttercup). `buttercup` is available from MELPA and most recommend for general use by irc.freenode.net#emacs from 2019-2020Q1 (now current). It appears to work well with Emacs 27 pre-release and 28 e.g. build of GNU Emacs from git master.

While its semantics follow BDD and therefore impose some potentially undesired test design, this solution above all is robust and aggressively maintained. It is also depended upon by many heavily used Emacs projects such as [projectile](https://github.com/bbatsov/projectile/blob/master/test/projectile-test.el).

P.S. For questions like "Why not ERT?" see [buttercup's answer](https://github.com/jorgenschaefer/emacs-buttercup#why-not-ert).

/cc @jschaf

**Comment by jschaf** [comment]
Sure, I choose ert because it seemed to be the winner a few years ago.  Since buttercup is actively maintained, I think it's a good choice to switch to that.

**Comment by sergeyklay** [comment]
@jschaf Could you please create `CODECOV_TOKEN` variable inside https://github.com/jschaf/esup/settings/secrets with a value from https://codecov.io/gh/jschaf/esup

I plan to enable code coverage report for each PR. So that we'll see comments like this: 

![image](https://user-images.githubusercontent.com/1256298/76908529-9403d280-68b1-11ea-81a2-fec88eb3156d.png)

**Comment by jschaf** [comment]
I added the token. Let me know if it doesn't work.

**Comment by sergeyklay** [comment]
Works like a charm. Thank you!
