### ISSUE TITLE
Cannot open load file: No such a file or directory, s

### ISSUE THREAD

**Issue by jcs090218** [jschaf/esup#81]
Continue to this thread #63. I think is better to open it on another issue.

I think the patch from #80 will occurs the error below. 😕 

```
Cannot open load file: No such a file or directory, s
```

---

**Edit:** 

Just to clarify, this error occurs after `M-x esup`.

**Comment by pRot0ta1p** [comment]
Have the same problem here after upgraded to Emacs 27.1

**Comment by benley** [comment]
As a quick workaround, try manually installing the `s` library: https://melpa.org/#/s

**Comment by jcs090218** [comment]
I don’t think you could? Cuz once esup is enabled everything starts from scratch! I think is about the load path isn’t ready, and you are trying to load s lib. Maybe try package-initialize at the start of esup? Or extract the functions you use from s lib and implemented locally?

**Comment by sergeyklay** [comment]
I hope this fixed now.

**Comment by sergeyklay** [comment]
@jcs090218 Could you please check now?

**Comment by jcs090218** [comment]
Nope, it didn't work.
