### ISSUE TITLE
Emacs 27.1 unnecessary (package-initialize) error

### ISSUE THREAD

**Issue by jcs090218** [jschaf/esup#84]
Emacs version above `27.1` you won't need to do `(package-initialize)` like the code snippet below.

```el
(when (version< "27.1" emacs-version)
  (package-initialize))
```

But this cause the error for `esup`. Yet if I just called `(package-initialize)`, then everything work fine.

**Comment by kiennq** [comment]
You can use something like this
``` elisp
  (when (or (version< emacs-version "27.0")
            (featurep 'esup-child))
    (package-initialize))
```

**Comment by jcs090218** [comment]
This resolved my issue! Thanks!  Close this now.
