### ISSUE TITLE
Support foldable tree view

### ISSUE THREAD

**Issue by wasamasa** [jschaf/esup#9]
I've found out the other day that Emacs' profiler.el actually uses foldable trees in its report view. If you move point to the item you're interested in and hit RET, it opens it up so that you can see the offending parts better.

It would be pretty awesome to have the same debugging support in esup, simply because that way one has no longer to replace top-level forms executing other top-level forms in the init just to find the problematic spots. The code for the UI could be borrowed from profiler.el, I'm not sure about the changes needed for the backend. What do you think?

**Comment by jschaf** [comment]
Hey, sorry about the three year delay.  A tree-folding view would be nice but it'd be a decent chunk of work and I'm mostly happy with the minimalist interface at the moment.

I think for profiling start-up files, the common case is finding the most expensive lines.
